language: cpp

# compilers to add to build matrix
compiler:
  - clang

before_install:
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
  - sudo apt-get install -qq cppcheck


install:
  - sudo apt-get install libcv-dev libcvaux-dev libhighgui-dev libopencv-dev
# scripts to run before build
before_script:
  - mkdir build
  - cd build
  - cmake ..

# build app, and run tests (ie make & make test)
script:
  - cmake --build .
  - ctest --output-on-failure
